# Generated by Django 3.1.7 on 2021-06-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
