# Generated by Django 3.1.7 on 2021-07-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210627_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_url',
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
